# Everything can be modified using /mapresetplugin.
# This file does not need to be modified.
world: null
source:
  x: null
  y: null
  z: null
  x2: null
  y2: null
  z2: null

target:
  x: null
  y: null
  z: null
  x2: null
  y2: null
  z2: null

playerteleportylevel: null

resetdelay: null

announcereset: "subtitle"